In [1]:
import numpy as np


In [9]:
my_list = [1,2,3,4,5,6]
myArray = np.array(my_list,dtype = int)
print(myArray)
# myArray.shape
myArray.ndim

[1 2 3 4 5 6]


1

In [12]:
myArray.reshape(3,2)
myArray.shape

(6,)

In [14]:
a = range(24)
a

range(0, 24)

In [16]:
aArray = np.array(a,dtype = int)
aArray


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [21]:
aArray.reshape(8,3,1)

array([[[ 0],
        [ 1],
        [ 2]],

       [[ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11]],

       [[12],
        [13],
        [14]],

       [[15],
        [16],
        [17]],

       [[18],
        [19],
        [20]],

       [[21],
        [22],
        [23]]])

In [29]:
my_list1 = [1,2,3,4,5]
my_list2 = [6,7,8,9,10]
myArray1 = np.array(my_list1,dtype = int)
myArray2 = np.array(my_list2)
re =print(myArray2-myArray1)
print(myArray1*myArray2)
print(myArray1+myArray2)
print(myArray1/myArray2)
print(myArray1%myArray2)



[5 5 5 5 5]
[ 6 14 24 36 50]
[ 7  9 11 13 15]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[1 2 3 4 5]
